version: "3.8"

services:
    postgres:
        image: postgres:17-alpine
        container_name: innovation_brindes_container
        environment:
            POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
            POSTGRES_USER: postgres
            TZ: UTC
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
        ports:
            - "5456:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

volumes:
    postgres_data:
